'use strict';
/**
 * Unit Tests for lib/quality/regression-guard.js
 * 15 TC | console.assert based | no external dependencies
 */

const fs = require('fs');
const path = require('path');
const os = require('os');

// Set up tmp dir and mock platform
const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'bkit-regguard-test-'));
const stateDir = path.join(tmpDir, '.bkit', 'state');
fs.mkdirSync(stateDir, { recursive: true });

const platformPath = require.resolve('../../lib/core/platform');
const origPlatform = require(platformPath);
const mockPlatform = { ...origPlatform, PROJECT_DIR: tmpDir };
require.cache[platformPath] = { id: platformPath, filename: platformPath, loaded: true, exports: mockPlatform };

let mod;
try {
  mod = require('../../lib/quality/regression-guard');
} catch (e) {
  console.error('Module load failed:', e.message);
  process.exit(1);
}

let passed = 0, failed = 0, total = 0, skipped = 0;
const failures = [];

function assert(id, condition, message) {
  total++;
  if (condition) { passed++; console.log(`  PASS: ${id} - ${message}`); }
  else { failed++; failures.push({ id, message }); console.error(`  FAIL: ${id} - ${message}`); }
}

// Helper: reset rules file
function resetRules() {
  const rulesPath = path.join(stateDir, 'regression-rules.json');
  if (fs.existsSync(rulesPath)) fs.unlinkSync(rulesPath);
}

console.log('\n=== regression-guard.test.js ===\n');

// --- RG-001~004: loadRules/addRule ---

resetRules();
const emptyRules = mod.loadRules();
assert('RG-001', Array.isArray(emptyRules) && emptyRules.length === 0, 'loadRules returns empty array when no rules');

const id1 = mod.addRule({
  category: 'api',
  description: 'Must use v2 API endpoints',
  severity: 'high',
  detection: { type: 'pattern', pattern: '/api/v1/' },
  detectedInFeature: 'feat-a',
});
assert('RG-002', typeof id1 === 'string' && id1.startsWith('RR-'), 'addRule returns rule ID with RR- prefix');

const id2 = mod.addRule({
  category: 'security',
  description: 'No plaintext passwords',
  severity: 'critical',
  detection: { type: 'pattern', pattern: 'password=' },
  detectedInFeature: 'feat-a',
});

const rules = mod.loadRules();
assert('RG-003', rules.length === 2, 'Two rules loaded after adding two');

const filteredRules = mod.loadRules('feat-a', 'security');
assert('RG-004', filteredRules.length === 1 && filteredRules[0].category === 'security',
  'loadRules filters by feature and category');

// --- RG-005~008: addRulesFromIteratorResult ---

resetRules();
const iterResult = {
  fixes: [
    { description: 'Fixed missing error handling', category: 'architecture', severity: 'high' },
    { description: 'Fixed SQL injection', category: 'security', severity: 'critical' },
    { description: 'Fixed naming convention', category: 'naming', severity: 'low' },
  ],
};

const createdIds = mod.addRulesFromIteratorResult(iterResult, 'feat-iter');
assert('RG-005', createdIds.length === 3, 'addRulesFromIteratorResult creates 3 rules from 3 fixes');
assert('RG-006', createdIds.every(id => id.startsWith('RR-')), 'All created IDs have RR- prefix');

const autoRules = mod.loadRules('feat-iter');
assert('RG-007', autoRules.length === 3 && autoRules.every(r => r.autoGenerated === true),
  'Auto-generated rules marked correctly');
assert('RG-008', autoRules.some(r => r.description.includes('Prevent recurrence')),
  'Auto-generated rules have prevention prefix');

// --- RG-009~012: detectRegressions ---

resetRules();
// Add metric-based rules
mod.addRule({
  category: 'performance',
  description: 'Match rate must not drop below 80',
  severity: 'high',
  detection: { type: 'metric', metricId: 'M1', op: '<', threshold: 80 },
  detectedInFeature: 'feat-perf',
});

mod.addRule({
  category: 'architecture',
  description: 'Critical issues must be zero',
  severity: 'critical',
  detection: { type: 'metric', metricId: 'M3', op: '>', threshold: 0 },
  detectedInFeature: 'feat-perf',
});

// No regression
const noRegression = mod.detectRegressions({ M1: 90, M3: 0 });
assert('RG-009', noRegression.detected === false && noRegression.regressions.length === 0,
  'No regression detected when metrics are good');

// M1 regression
const m1Regression = mod.detectRegressions({ M1: 75, M3: 0 });
assert('RG-010', m1Regression.detected === true && m1Regression.regressions.length === 1,
  'Regression detected when M1 < 80');
assert('RG-011', m1Regression.regressions[0].metricId === 'M1' && m1Regression.regressions[0].currentValue === 75,
  'Regression hit has correct metricId and currentValue');

// Multiple regressions
const multiRegression = mod.detectRegressions({ M1: 70, M3: 3 });
assert('RG-012', multiRegression.detected === true && multiRegression.regressions.length === 2,
  'Multiple regressions detected simultaneously');

// --- RG-013~015: pruneStaleRules ---

resetRules();

// Add old rule with 0 violations (should be pruned)
mod.addRule({
  category: 'naming',
  description: 'Old stale rule',
  severity: 'low',
  detection: { type: 'pattern', pattern: 'old' },
  detectedInFeature: 'feat-old',
  createdAt: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000).toISOString(), // 100 days ago
  violations: 0,
});

// Add old rule with violations (should be kept)
mod.addRule({
  category: 'security',
  description: 'Old active rule',
  severity: 'high',
  detection: { type: 'pattern', pattern: 'active' },
  detectedInFeature: 'feat-old',
  createdAt: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000).toISOString(),
  violations: 5,
});

// Add recent rule with 0 violations (should be kept)
mod.addRule({
  category: 'api',
  description: 'Recent rule',
  severity: 'medium',
  detection: { type: 'pattern', pattern: 'new' },
  detectedInFeature: 'feat-new',
});

const pruned = mod.pruneStaleRules(90);
assert('RG-013', pruned === 1, 'pruneStaleRules removes 1 stale zero-violation rule');

const remaining = mod.loadRules();
assert('RG-014', remaining.length === 2, 'Two rules remain after pruning');
assert('RG-015', remaining.every(r => r.violations > 0 || r.description === 'Recent rule'),
  'Remaining rules are either active (violations>0) or recent');

// --- Cleanup ---
delete require.cache[platformPath];
fs.rmSync(tmpDir, { recursive: true, force: true });

// --- Summary ---
console.log(`\nResults: ${passed}/${total} passed, ${failed} failed, ${skipped} skipped`);
if (failures.length > 0) {
  console.log('Failures:');
  failures.forEach(f => console.log(`  - ${f.id}: ${f.message}`));
}

module.exports = { passed, failed, total, skipped, failures };
